version: '2'

services:
  app:
    build: ./app
    links:
      - pg

  pg:
    image: postgres:9.5
    volumes_from:
      - pg_data_box

  pg_data_box:
    image: busybox
    volumes:
      - /var/lib/postgresql/data

  migrator:
    image: hiogawa/standalone-migrations:4.0.3
    links:
      - pg
    volumes:
      - ./db:/app/db
